api_platform:
    title: 'UR-Shortener API'

    # The version of the API.
    version: '1.0.0'

    # Set this to false if you want Webby to disappear.
    show_webby: false

    formats:
        jsonld:
            mime_types: [ 'application/ld+json' ]

        html:
            mime_types: [ 'text/html' ]

    error_formats:
        jsonld:
            mime_types: ['application/ld+json']
